### ISSUE TITLE
Allow Facilitator to enforce Partner Agreements during governance

### ISSUE THREAD

**Issue by brianjrobertson** [holacracyone/Holacracy-Constitution#266]
As a Facilitator during the reaction round, if someone is stating a judgment or experience as fact, or projecting without calling it out as a projection (or inference, story, or similar distinction), then I'd like the constitutional power to able to stop that and redirect them to sharing while fully [owning their experience](http://integralcenter.org/owning-your-experience/).  Thus, I'd like them to be able to share anything coming up for them in their experience, even their projections and judgments, but only if they share them cleanly by calling them out for what they are vs. describing them as objective truth; if they fall short of this, then I'd like the authority to interrupt to remind them to own their experience and invite them to try again (but not to stop them from sharing it).

**Comment by bernardmariechiquet** [comment]
Wow! Love it and at the same time, I think that sets the bar very high for many people who do not have this awareness of themselves and others, nor the tools to acquire this for taking responsibility for their feelings, needs and values, this ability to make observations without interpretation or judgment and this ability to make explicit requests. I do not see how the Facilitator could intervene during a reaction in such a situation of such tool/syntax not being used. A simple model such as NVC (Owning your experience seems to me very close to NVC process with which I'm very familiar) or even simpler rules such as "speak to I" "do not judge/interpret" etc that are explained and accepted by everyone upstream in the process because they would make sense to them even outside the meetings, would no doubt be needed. And so the Facilitator could sound a gong for example to remind the rules of the game to the one who speaks and who could speak again at the end of the sound of the gong. 
It would be nice and at the same time I wonder @brianjrobertson what is the tension behind your proposal. Could you share some examples that show the absence of such new language structure would cause harm to the org., I am very concerned not to project on others a mode of communication and personal values that would not really be indispensable for the organization to demonstrate its evolutionary purpose.

**Comment by chrcowan** [comment]
@brianjrobertson Hmmm...interesting. I think I love it. lol. But how could this even be considered for a constitutional change, when as far as I know, it's never been experimented with? I like the idea of experimenting with it for sure, but I don't know if I'm capable of having enough data or a strong enough opinion (either way) to meet the standard I would imagine is required for a change to the constitution.

**Comment by brianjrobertson** [comment]
Re:

> I think that sets the bar very high for many people who do not have this awareness of themselves and others, nor the tools to acquire this for taking responsibility for their feelings, needs and values, this ability to make observations without interpretation or judgment and this ability to make explicit requests.

I'm not sure I resonate with that.  They can still just show up and talk; the idea is to give the Facilitator the power to interrupt with simple requests, like asking them to restate an opinion or experience as an opinion or experience if stated as a fact.  The goal isn't to say they can't talk without doing this, nor to give the Facilitator the ability to simply stop them outright, but just to redirect and guide them to languaging to use instead.  I'll need to make that clear when actually implementing this; it wouldn't be a good thing if the Facilitator could simply stop them without a redirect.

> A simple model such as NVC (Owning your experience seems to me very close to NVC process with which I'm very familiar) or even simpler rules such as "speak to I" "do not judge/interpret" etc that are explained and accepted by everyone upstream in the process because they would make sense to them even outside the meetings, would no doubt be needed.

Agreed, to implement this, it needs to get broken down into more concrete/clear rules.  And yes, NVC is another take on the same general principles - my intent here isn't to suggest encoding one or the other directly, but just to distill down to a simple key rule that captures something of the wisdom in them.

> It would be nice and at the same time I wonder @brianjrobertson what is the tension behind your proposal. Could you share some examples that show the absence of such new language structure would cause harm to the org., I am very concerned not to project on others a mode of communication and personal values that would not really be indispensable for the organization to demonstrate its evolutionary purpose.

I've felt this tension myself as a Facilitator numerous times now.  I see cases where someone starts effectively dumping judgments on someone else in a reaction, while stating them as if facts (or sometimes when presenting the tension behind a proposal, or in integration - perhaps we need this rule in those places too; or just anywhere in the meeting processes).  That then sends the other person into a defensive attacking-back mode, which makes integration way harder, and seems to leave people with a bad taste for the whole process - it kills some of the felt safety of the process.  In those cases I've wished I could step in and simply redirect them to using I language and speaking from their experience vs. judging as if fact; I think it would have protected others' sense of safety with a very simple facilitator move, while also helping the judger not get stuck in the judgment and have a better experience too.  But I had no constitutional ground to stand on to do so.  So, there's a real tension there with several real examples I've run into myself...

> But how could this even be considered for a constitutional change, when as far as I know, it's never been experimented with?

The requirement I'm holding is that there's a real, grounded tension behind it, not necessarily that the solution has been experimented with, unless it seems particularly risky.  Or rather, the path to do the experimentation is during the 5.0 beta testing process; there are many changes already in the draft 5.0 that haven't been tested yet; I only hold a bar of requirement experimentation first for more dramatic potential changes.

**Comment by bernardmariechiquet** [comment]
> That then sends the other person into a defensive attacking-back mode, which makes integration way harder, and seems to leave people with a bad taste for the whole process - it kills some of the felt safety of the process. In those cases I've wished I could step in and simply redirect them to using I language and speaking from their experience vs. judging as if fact; I think it would have protected others' sense of safety with a very simple facilitator move, while also helping the judger not get stuck in the judgment and have a better experience too.

Crystal clear, make total sense to me!

This should probably be a more general rule applicable in all steps of the governance meeting and not only during the reaction round, and also applicable to all meetings, (may be also including any interaction between people outside the usual meetings). And that makes a lot of sense to me.
This subject would therefore have to be dealt with in a new specific area of the constitution which would concern rules of communication between persons. May be this is the sign of beginning to incorporate into the constitution things about agreements between people.

**Comment by brianjrobertson** [comment]
Agreed that it should be generalized to cover all meetings, but not that it should be generalized into an agreement to speak that way to other partners in general; that sets a *very* high bar, and sets up others to blame them for violating an agreement when they inevitably slip.  This is a really important distinction I think: the change I'm suggesting is not asking the person to agree to talk that way at all, it's just giving the Facilitator the authority to interrupt them and hold rules for a space such that they must talk that way in order to say the thing they want to say.  I think that's actually far more powerful, in that it isn't asking the participant to be "more evolved" in how they deal with emotions and triggers; it's just creating the space and conditions that hold up a mirror to the lack thereof and create internal motivation to want to align with some new behavioral norms, so that their voice can be heard.

**Comment by chrcowan** [comment]
> The requirement I'm holding is that there's a real, grounded tension behind it, not necessarily that the solution has been experimented with, unless it seems particularly risky. Or rather, the path to do the experimentation is during the 5.0 beta testing process; there are many changes already in the draft 5.0 that haven't been tested yet; I only hold a bar of requirement experimentation first for more dramatic potential changes.

@brianjrobertson gotcha. Well, then maybe it comes down to the specific phrasing used because I can envision facilitators using it inappropriately. It could be a can of worms. Random top-of-head options: 

- Just use the phrase "owning one's experience" and leave the rest up to interpretation/training/coaching/best practice. 

- Use something like "reactions must be worded in a way that can't be argued." I really liked that phrasing.

Or maybe you redefine what a "reaction" is or what the "reaction round" is about. That could be really simple. Just add something subtle in there which most people might not even notice to give you the grounds you're looking for.

**Comment by bernardmariechiquet** [comment]
May be a simple rule like "speaking in the first person singular" to express and own one's experience.

**Comment by brianjrobertson** [comment]
@bernardmariechiquet That wouldn't accomplish the goal; e.g. "I know John is an idiot with a big ego, and is proposing this just to get more personal power".

**Comment by bernardmariechiquet** [comment]
@brianjrobertson Sure! What about adding to 3.4.5 something like "The facilitator may also stop and disallow any impugn motives, any interpretations, or any constraints, and invite the participant to own his experience by expressing in place feelings, facts, or effects he has lived."

**Comment by brianjrobertson** [comment]
I don't think we want the facilitator judging motives, nor disallow interpretations, projections, or judgments (just require them to be called out and owned as such).

**Comment by bernardmariechiquet** [comment]
@brianjrobertson So, what do you suggest?

**Comment by chrcowan** [comment]
I don't think I can provide very good feedback until I know the proposed wording. 

FWIW - In my mind, I'm thinking of a use-case like, Reaction: "I think this makes sense.....yeah, it's a good proposal." This first part of which fits the definition, but the second half doesn't. And the argument for context-clues affecting interpretation is the same for the Reaction Round itself (i.e. by definition it's each individual's experience/perception).

**Comment by brianjrobertson** [comment]
@chrcowan The wording I'll propose will likely **_allow_** the facilitator to cut off and require the latter half of that example to be reframed, but it will not demand the facilitator do so or that the participant not use it; from there, if any facilitator actually does decide to nitpick at that level (hard to imagine, but possible) and it gets in the way of the group, well, that's why anyone can call for a new election at any time...

**Comment by oliviercp** [comment]
@brianjrobertson That's really interesting, and I share @bernardmariechiquet's concerns of a high bar. I've experienced that same tension as facilitator, and have seen people get defensive as a result of judgements shared in reactions, integration, or even (actually at least as often) in the closing round. 

On one hand, I think it's too high of a bar for the facilitator -- they have to be able to make those distinctions in order to detect the judgements, and I'm constantly reminded how many people just don't _see_ these distinctions. Facilitation is already difficult, so it would add the need for an even more subtle understanding of communication dynamics to be a good facilitator. 

On the other hand, I wonder how something like that could be some optional/fall back process, a bit like the advanced rules of integration are. Something the facilitator can choose to ignore -- and would likely ignore most of the time -- but could rely on if things get difficult. 

This is my current thought

**Comment by brianjrobertson** [comment]
@ocompagne I don't think it raises the bar for facilitator at all; the goal is not to require the facilitator to do that or expect them to do that, just to allow them to cut-off and redirect those things if they happen to notice them and happen to choose to use that power.  So, to your point, yes, the vision is absolutely that they could ignore it entirely.

**Comment by oliviercp** [comment]
@brianjrobertson I understand; I still think that even if it's an optional rule, meeting attendees may like to rely on it, and as Facilitator it would feel like something that needs to be in my toolkit to be a "good Facilitator" and not let my team down. 

That's not necessarily bad, I see pros and cons. The con is that it puts the bar higher to be an excellent facilitator (which is already quite high), but the pros are that it raises awareness about these distinctions, and about the need for that capacity to make them.

**Comment by bernardmariechiquet** [comment]
One might then imagine, in order not to set the bar too high for the facilitator and so that the team does not feel at the mercy of the facilitator's ability alone, to allow any participant who would notice them to cut-off and redirect those things.

**Comment by brianjrobertson** [comment]
Allowing anyone to cut them off sounds like it could get chaotic real quick, not so sure about that...

**Comment by bernardmariechiquet** [comment]
@brianjrobertson I understand, you're pointed out one of the cons of such solution.

**Comment by chrcowan** [comment]
@brianjrobertson I'm still concerned about this somehow making it into the rules, but I could see "owning your experience" as a great best practice to share as good ways to communicate during your reaction. 

Others that come to my mind include: avoid generalizations (e.g. "This is needed") and make concrete suggestions (e.g. "maybe 'Publishing' would be a better fit.") but again, I don't think these heuristics are appropriate at the rule level. 

To me, it seems like you're making the reactor responsible for how other people react. And that seems backward. If someone is just dumping judgments and you're worried that it _might_ make the proposal more likely to feel defensive, and you feel somehow like you need to intervene, then why not just take a timeout? 

From that space, you could provide whatever coaching you think appropriate to the situation; which of course is no different than calling a timeout during any other step to deal with any other issue. 

However, I did notice that [the current definition](https://www.holacracy.org/constitution#art335) doesn't mention anything about "neutrality," but I'll often say things like, "provide your reaction neutrally to the space -- not other people." Maybe if you had that, you could then interpret a real epic public shaming via judgment as not being neutral, giving you cause to redirect. Thoughts?

**Comment by brianjrobertson** [comment]
@chrcowan, re:

> To me, it seems like you're making the reactor responsible for how other people react. 

How so?  I'm not seeing it.  Owning your experience requires no ownership of how others react.  It's just about speaking cleanly; others can still hear uncleanly.  And in this case, I'm not proposing the reactor has to do anything differently; just that the facilitator can nudge their language towards something more clean if it isn't already.

> If someone is just dumping judgments and you're worried that it might make the proposal more likely to feel defensive, and you feel somehow like you need to intervene, then why not just take a timeout?

Under the current rules, I'd say taking a timeout to coach around that would be bordering on outside the authority of the facilitator, and definitely a bad practice.  What I'm going for here is a simple rule that would actually let me do that as facilitator.

> However, I did notice that the current definition doesn't mention anything about "neutrality," but I'll often say things like, "provide your reaction neutrally to the space -- not other people." Maybe if you had that, you could then interpret a real epic public shaming via judgment as not being neutral, giving you cause to redirect. Thoughts?

That's headed in the right direction I think, but it seems super vague and easy to interpret in ways that would let the facilitator redirect something the facilitator shouldn't, like a reaction that is negatively judging the proposal but from clean language/ownership.  And note I'm not just trying to catch epic public shamings here; I think a skilled facilitator even catching "normal" unowned experience and giving a super-quick reminder to, say, "speak from I statements" in the right moment could be incredibly powerful and help create the culture needed for Holacracy practice to thrive.

**Comment by denniswittrock** [comment]
I am wondering a bit about the motivation behind "correcting" somebody's reaction. While I get that this is meant to avoid emotional escalation and holding people to saner standards of communication it also limits people's right to express whatever they want to say and however they want to say it. I like about the current version of the constitution that it grants that kind of freedom to the reactor - even if others might get triggered. 

Extending the rights of the facilitator to interrupt here crosses dangerously into the "speech and thought -police" territory. If such a right exists, many will likely interpret it as an invitation to censor others. That may backfire despite the best intentions. Communication skills, awareness, and abilities to judge speech differ greatly and depend on individual development. Think of green political correctness. Just as it is not the job of the facilitator to prevent objections, it should not be the job to prevent free expression during reactions - even if it triggered somebody else unnecessarily. It raises the question of who is allowed to judge who.

I like about the reaction round that every statement is simply bracketed. Say whatever you want to say, however you want to say it, let off steam, be super-clever, be disinterested, be positive, neutral, don't know - all is fine. If my colleague wants to rip my proposal apart and be judgemental about it - fine. I don't need "saving" by the facilitator, thanks. I think I can take it if we just bracket it - like all reactions are simply bracketed. It is a non-issue. My worry is that if we don't bracket it, but start judging the contents of reactions (even if not on a regular basis), that this very intervention (or potential thereof) will make the space feel not more safe but *less* so. Focusing on communication might become a distraction from getting the work done. 

Holacracy deals with the work of the Organization and leaves the people alone - with all upsides and downsides. Taking care of the people and the culture is a matter of what we at encode.org would consider the domain of the Association. It is based on opting in to certain norms and standards of speech that could be encoded here in the form of explicit agreements. Since Organization, Company and Association are overlapping spheres, those values - our human dimension, the values and norms of speech and conduct we hold each other accountable to - would also be present during a Governance meeting. A timeout could be taken to remind people of a certain way of speaking as part of the Association agreement - if such exists in this firm. This way, Holacracy and its ruleset would not be fraught with having to deal with the "people stuff" - epicycles, like in ancient astronomical theories.  

For me it feels wrong to force it into the constitution. What makes the constitution such an inspiring and fruitful document is that it fosters the differentiation of role and soul, of the organizational and personal purpose, of the different "Spaces". It doesn't attempt to cover every dimension. It focuses on the work and the organization, refusing to interfere in the personal and interpersonal realm. My pitch is to leave it this way. 

But needless to say, this is just my momentary personal take and I could be wrong about any of this. :-)

**Comment by brianjrobertson** [comment]
Thanks @denniswittrock, I do share your concern here, and that's definitely the issue/risk I'm trying to sense into and weigh against the value of a slight nudge towards cleaner language and awareness of projection/judgment.

**Comment by cassus** [comment]
After reading the comment from @denniswittrock I'm thinking of how to have both the differentiation of Org and Association _and_ better integration.

I'd like the Facilitator to have the power in-process (without timeout) to remind and re-direct people to own their experiences. Yet this also seems to cross-over to Association and I'd like Holacracy to be compatible with both Green, pre- and post- Green cultures and what/how to redirect depends a lot on the culture.

I'm seeking how to create integration points between Hola and the Association agreement. How about having the facilitator right to cut-off and redirect someone not "owning their experience" as a default that can be changed not by a policy (governing the org) but the association agreement (governing the people)?
Maybe creating a bridge between the Governance Facilitator role and the "Association Facilitator" role, acknowledging the presence of this second function even during Hola meetings, differentiating but also allowing for integration?

**Comment by LouisChiquet** [comment]
I totally second @denniswittrock's comment. @brianjrobertson took as example “_e.g. "I know John is an idiot with a big ego, and is proposing this just to get more personal power"._”, well, I don't see any issues with this. I mean, in some organisations it'll pass perfectly, it's just a question of culture. In fact, during a meeting in iGi and somebody was doing a proposal that I already escalated during the Gov out of Gov, I had a terrible reaction (but using the rule @bernardmariechiquet said of not engaging and not using “you” directed at somebody) and was really emotional about the proposal. But I really needed this space of expression, which I fear with your proposals on this issue would have been interrupted and made me even more emotional, and not feeling confortable to express myself or even release my energy. Because the reaction allowed me to, when I had my 6 objections, be way more cool during the integrations because I said what I needed to say. So I totally feel like it'd cause harm to do such amendment which would go further then the simple “_no engagement and no “you”_”.

**Comment by brianjrobertson** [comment]
I'm wondering if implementing this in a more meta way would make more sense, or be too dangerous; e.g. instead of directly allowing the facilitator to redirect people not "owning their experience", have a rule that enables the Facilitator to enforce any Working Agreement made among the participants while facilitating any meeting, as long as they don’t interfere with the basic function/goal of each step of the gov or tactical process.  Thoughts?

**Comment by chourie2** [comment]
I like the idea ! I don’t know if it should be seen like this, but for me WA are a way to allow other, if needed, to challenge me on the agreements that I took.

I’m wondering if the relation to the process should be reversed. Something like « as long as enforcing the WA make sens with the basic function/goal of the current step of the gov or tactical process ». It’s even more restrictive, and I don’t have any example that motivate such change, but I feel like it could be safer, as long as the interpretation on the « basic function/goal » is simple and clear for each step (which I think it is).

And maybe I didn’t get it right as a non-native English speaker, but the facilitator can only enforce a WA to someone who have took it right ? I’m not sure how to read the « enforce any WA made among the participants » in that regard!

**Comment by brianjrobertson** [comment]
I've been reflecting on this one for awhile, and just reread the thread above as well, and my current intent is to implement what I described in my last comment above, plus perhaps in addition consider one of these approaches that @chrcowan suggested, specifically for the reaction round:

> Just use the phrase "owning one's experience" and leave the rest up to interpretation/training/coaching/best practice.

> Use something like "reactions must be worded in a way that can't be argued." I really liked that phrasing.

Any thoughts on which of those might be worth pursuing, or concerns about either?

**Comment by brianjrobertson** [comment]
I just submitted a change to implement the approach in my comment a few above; if anyone wants to review, I'd love any opinions.  And then I still have the open question in my comment immediately above as well.

**Comment by klaas1979** [comment]
I like the change: it has enough process to really cut into issues if need be and it does not enforce any special way to do it. It should integrate people-space issues into the organization-space as needed on a per circle basis.

Just one thought: new circles or organizations will not understand the mechanism. It will need an App or good examples to explain what can be done by this sentence and how an adequate working agreement may be phrased.

**Comment by LouisChiquet** [comment]
I believe for new circles or orgs, that they won't, in the first months, use the working agreements if they don't have a tension for, as it's also something new and demands time to integrate (like many tools of the Holacracy Constitution) therefore as a coach I wouldn't dive into the details or even explain. When they'd have a tension, I'd develop further into this, but would depend of them. Plus, you can't explain or push all the rules Holacracy has at once.

On this change, that I appreciate, I consider it strange, because I suspect some working agreements may be “private”, I mean, defined on one to one, and if such, I'd hardly find it possible that the facilitator knows those and enforce them, plus feel weird that it'd apply certain rules to certain individuals but not everybody while all the people are in the same meeting, because of special one to one working agreements.

**Comment by ericdgraham** [comment]
I haven't read this full thread thoroughly but skimmed some of it. I think this crosses a line and gets into correcting people's communication in a way that goes beyond the scope of the facilitator's role of holding to the Holacracy process. You'd almost need an entire section of the constitution dedicated to responsible communication to expect others to have that capacity and reasonably have the authority to hold them to it. 
I also think this will significantly increase the potential for charged conflict between reactor and facilitator. If the reactor if actually speaking from an emotional reaction, the facilitator would need a lot of capacity to clearly cut them off, coach them, and successfully manage the interaction.
I also like that Reactions are open-ended. It allows each person the space to share from where they're at and each person receiving it has to do their own filtering. But everyone is taking care of themselves, which I think is an element of that round.

**Comment by chrcowan** [comment]
I think this is your solution right here, "...have a rule that enables the Facilitator to enforce any Working Agreement made among the participants while facilitating any meeting." I think that gets the benefits without creating the (potential) harm.

**Comment by brianjrobertson** [comment]
@chrcowan I've already implemented that, but I don't think it's sufficient to address the tension here.  So I'm also considering one of the two suggestions you floated here:

> Just use the phrase "owning one's experience" and leave the rest up to interpretation/training/coaching/best practice.

> Use something like "reactions must be worded in a way that can't be argued." I really liked that phrasing.

Any more thoughts on adding either of those, specifically/only for the reaction round?

**Comment by ericdgraham** [comment]
Of those two I like
> use the phrase "owning one's experience" and leave the rest up to interpretation/training/coaching/best practice.

Maybe add a simple line to the Reaction round framing: "Do your best to speak from your own experience."

**Comment by chrcowan** [comment]
@brianjrobertson of the two options, I think "owning one's experience," is better but again, I'd have to see the specific phrasing proposed.  

Now, I still have a concern which I'' share in response to your earlier question...

> @chrcowan, re:
> 
> To me, it seems like you're making the reactor responsible for how other people react.
> 
> How so? I'm not seeing it. Owning your experience requires no ownership of how others react. It's just about speaking cleanly; others can still hear uncleanly. And in this case, I'm not proposing the reactor has to do anything differently; just that the facilitator can nudge their language towards something more clean if it isn't already.

First, the reason it seems like you're making the Reactor responsible is because the focus isn't on the person who may be having a strong reaction to what the Reactor says. That's basically a reaction to a reaction which is disallowed already, so purely as a Facilitator following the rules, I don't see where that surfaces officially in my handling of the process. Meaning, this stuff is more appropriately handled as a "Coach." Maybe that's not a meaningful distinction, I don't know. 

Second, I haven't experienced a case in which this would be needed, so I'm not in touch with the tension, so take this with a grain of salt, but in the example you gave above, "I know John is an idiot with a big ego, and is proposing this just to get more personal power," I don't see why a change would be needed since this clearly violates the rule already (or you could make that case), i.e. "...each participant except the Proposer may share reactions to _the Proposal_," and this statement is about the person, not _the proposal_. 

Thirdly, creating a rule kinda boxes me in as a Facilitator. I know you said, "@chrcowan The wording I'll propose will likely allow the facilitator to cut off and require the latter half of that example to be reframed, but it _will not demand the facilitator do so_ or that the participant not use it;" so I'm curious on the specifics, because when I think about changing the current way the Reaction Round is defined, "...The Facilitator _must_ immediately stop and disallow any out-of-turn comments, any attempts to engage others in a dialog or exchange of any sort, _and any reactions to other reactions_ instead of to the Proposal," it means that I don't have a choice in the matter. Any more than I have a choice on whether to stop dialog. If I don't notice that someone is reacting to a Reaction, fine, but if I do notice it, then I'm obligated to, "immediately stop and disallow." You're probably already accounting for that because of what you said, but I'm highlighting it here to **underscore the importance of knowing the specifics of the entire passage you're working from**. 

Now, given all of that, if you simply added a line at the end of the current section (i.e. keeping everything else the same), "The Facilitator may direct that a reaction be phrased in such a way that the reaction is clearly coming from their experience rather than an objective truth." Or something like that then I wouldn't have an issue with it since the word, "may" clarifies that the Facilitator can use their discretion.

**Comment by brianjrobertson** [comment]
How about a clause like this in a section covering the whole governance meeting process?:

> At all times during the meeting, the Facilitator must disallow and immediately stop any speaking by anyone except whoever is specifically invited to speak at that point in the process under the rules herein. The Facilitator may also interrupt an authorized speaker who states an inference or judgment as if a fact, and invite the speaker to restate their comment while owning their experience.

Thoughts?

**Comment by ericdgraham** [comment]
It gets more personal for the facilitator to interpret someone's language and then offer for them to correct their speech (even if it's just a suggestion). It could be trigger inducing and introduce conflict into the meeting process. That said, the way you've introduced it and the language feels like a light touch and I appreciate that it's optional for the facilitator to use judgment on when and how to interject. I personally probably wouldn't introduce it, but it seems like you're sensing something valuable here. Worth a try. I might try some experiments with it first.

**Comment by brianjrobertson** [comment]
@ericdgraham Thanks for the feedback; note my intention here is to require very minimal interpretation on the part of the facilitator - perhaps no more than is required for assessing a clarifying question vs. a reaction.   They'd just be listening for whether a statement is an inference or judgment (similar to listening for whether a question is really a reaction), and if it's not called out as such, they can choose to interrupt and invite the speaker to try again (just like if a CQ is really a reaction). And in this case, the intent is actually not to require it at all, just to allow it.

**Comment by brianjrobertson** [comment]
Hey Folks - At this point I'm leaning against adding the clause above or anything equivalent as just too risky, but I'd really love to hear arguments for it from anyone who thinks it would be useful and I shouldn't give up on it...

**Comment by diederickjanse** [comment]
We have been experimenting with what you might call "working agreements" at Energized.org, centered around interpersonal space (incl. communication, norms), and inspired by practices from Systems-Centered Training (SCT). The type of examples shared in this thread would definitely fall into this category, e.g. calling out assumptions being presented as facts and reality-testing them.

What we have found is that it takes different skills and expertise and serves a different purpose than the Facilitator role, and so we have created a separate role for that, called the [Process Leader](https://app.glassfrog.com/organizations/796/orgnav/roles/11076861/overview), which is an elected role as specified by a policy.

There's some very clear guidance from the SCT work on the relationship and prioritization of the Facilitator (similar to a Task Leader in SCT) and the Process Leader. Essentially, task always takes precedence, and so you wouldn't take a time-out to do process work (incl. a quick intervention to call out and reality-test an assumption) unless it was really necessary to move forward with the task. Also, the Task Leader makes the call of whether process work is needed, and for how long. This ensures that process work doesn't hijack the task work, e.g. a tactical or governance meeting.

My point in all this is that I think it's a different role, serving a different purpose, requiring different skills. The Facilitator executes the constitutionally defined meeting processes to enable circle members to reliably and systematically process tensions for their roles. The Process Leader's goal is identifying and undoing restraining forces so that participants continue to have enough of their resources and energy available to accomplish the task. Don't make that the Facilitator's job -- it dilutes the clarity and integrity of the role and raises the bar in a way that I think is neither helpful nor realistic.

**Comment by LouisChiquet** [comment]
I'd agree on going against adding the clause too.

@diederickjanse : Can't access the link you shared. May you copy/paste purpose/domain(s)/accountabilities of the role to see?
But so to resume well what I understood of your post, it shall be defined organically by the company as it may vary from a company to another, knowing that this concerns Humans and most importantly HR. Correct? So agreeing with Brian's message too.

**Comment by diederickjanse** [comment]
> @diederickjanse : Can't access the link you shared. May you copy/paste purpose/domain(s)/accountabilities of the role to see?

Sure!

Role: Process Leader
Purpose: All our energy and resources as members are available for the pursuit of the circle's purpose
Accountabilities:
- Facilitating ad hoc functional subgrouping when there is not enough energy available to accomplish a specific task
- Facilitating joining when (significant) differences emerge
- Identifying and undoing restraining forces (e.g. noise, predictions, mind reads, old [personal] roles, etc.)

And no @LouisChiquet, my main point is not for company's to define it themselves, like we did with the Process Leader. My main point is not to add this to the Facilitator role.

**Comment by brianjrobertson** [comment]
Thanks for the input everyone!  I'm going to leave this issue at just the little API-like hook I added around allowing enforcing Partner Agreements, and close this issue as done, without adding the extra bit contemplated above.
